version: '3.8'

services:
  proactive-assistant:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DEBUG=False
      - LOG_LEVEL=INFO
      - DEFAULT_TIMEZONE=Asia/Kolkata
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - assistant-network

networks:
  assistant-network:
    driver: bridge